faye/config/routes.rb
Rails.application.routes.draw do
  get 'chats/room'

  get  '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create'
  delete '/logout' => 'session#destroy', :as => :logout

  get '/chatroom' => 'chats#room', :as => :chat
  post '/new_message' => 'chats#new_message', :as => :new_message

end

faye/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def room
  	if session[:username].present?
  		respond_to do |format|
  			format.html
  		end
  	else
	  	redirect_to login_path
	  end
  end

  def new_message
	  # Check if the message is private
	  if recipient = params[:message].match(/@(\w+) (.+)/)
	    # It is private, send it to the recipient's private channel
	    @channel = "/messages/private/#{recipient.captures.first}"
	    @message = { :username => session[:username], :msg => recipient.captures.second }
	  else
	    # It's public, so send it to the public channel
	    @channel = "/messages/public"
	    @message = { :username => session[:username], :msg => params[:message] }
	  end

	  respond_to do |f|
	    f.js
	  end
	end
end

faye/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	def create
		  session[:username] = params[:username]
		  render :text => "Welcome #{session[:username]}!"
		end
  end

  def destroy
  	session[:username] = nil
  end
end

faye/app/helpers/chats_helper.rb
module ChatsHelper
end

faye/app/helpers/room_helper.rb
module RoomHelper
end

faye/app/helpers/sessions_helper.rb
module SessionsHelper
end

faye/app/views/chats/new_message.js.erb
// Clear message input
$('#message').val('');
$('<p></p>').html("me: " + "<%=  @message[:msg] %>").appendTo("#chat_room");

// Send the message
<% publish_to @channel, @message %>

faye/app/views/chats/room.html.erb
<div class="chat_container">
  <div id="chat_room">
    <p class="alert"> Welcome to the chat room <%= session[:username] %>! </p>
  </div>

  <%= form_tag new_message_path, :remote => true do %>
    <%= text_field_tag :message %>
    <%= submit_tag "Send" %>
  <% end %>
</div>

<%= subscribe_to "/messages/public" %>
<%= subscribe_to "/messages/private/#{session[:username]}" %>

<script>
  PrivatePub.subscribe("/messages/public", function(data) {
    console.log('xxxx', data);
    $('<p></p>').html(data.username + ": " + data.msg).appendTo('#chat_room')});

  PrivatePub.subscribe("/messages/private/<%= session[:username] %>", function(data) {
    console.log('xxxx', data);
    
    $('<p></p>').addClass('private').html(data.username + ": " + data.msg).appendTo('#chat_room')});
</script>